[package]
name = "mobility_protocol"
edition = "2024.beta"
license = "MIT"
authors = ["mgnfy-view (sahilgujrati12@gmail.com)"]

[dependencies.Switchboard]
git = "https://github.com/switchboard-xyz/sui.git"
subdir = "on_demand/"
rev = "testnet"

[addresses]
mobility_protocol = "0x0"
btc_usd_switchboard_aggregator = "0x5d86fb1cfe2d9d77ccc107f440f793115b02154006ccc4417d90b7fe0a22a2dc"

[dev-dependencies]

[dev-addresses]
